version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: xrazis/nodejs-project
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - node-network
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role==worker
      resources:
        limits:
          cpus: "0.50"
          memory: 50M
        reservations:
          cpus: "0.25"
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  node-network:
    driver: overlay
